AWSTemplateFormatVersion: 2010-09-09
Description: S3 provision

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: STD21028

    BucketNameSSM:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /s3/bucketName
        Type: String
        Value: !Ref Bucket
      DependsOn: Bucket

    BucketArnSSM:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /s3/bucketArn
        Type: String
        Value: !GetAtt Bucket.Arn
      DependsOn: Bucket
